# **NUMPY** (Numerical Python)

It is a python Library used for Numerical Computing

### **Difference between numpy arrays and Lists**

**Lists**
*  Can store different data types
*  Slower for numerical calculations
*  No advanced mathematical functions built in

**Numpy Arrays**
*  Designed for fast numerical computations
*  All elements must of the same data type
*  You do math on the whole array at once






In [ ]:
a = [32,20,16,12]
b = [20,43,21,45]
c = a+b
c

[32, 20, 16, 12, 20, 43, 21, 45]

In [ ]:
#Importing the Numpy Library
import numpy as np



**BASICS**

In [ ]:
# 1D
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D

b = np.array([[3,4,5,6],[4,3,5,6]])
print(b)

[[3 4 5 6]
 [4 3 5 6]]


In [ ]:
# 3D
c = np.array([
    [[2,3,4,5],[3,6,4,3]],
     [[7,4,3,2],[5,4,3,2]],
    [[4,3,4,5],[4,3,5,6]]
                          ])
print(c)

[[[2 3 4 5]
  [3 6 4 3]]

 [[7 4 3 2]
  [5 4 3 2]]

 [[4 3 4 5]
  [4 3 5 6]]]


In [ ]:
#Checking dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
# Get shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 4)
(3, 2, 4)


In [ ]:
# Get memory  size of each element in the array
print(a.itemsize)

8


In [ ]:
# Total space occupied by an array
print(a.size * a.itemsize)

24


**Accessing elements in the arrays**

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.ndim

2

In [ ]:
# Get a specific element
print(a[1,5]) #prints the element in the second row, fifth column

13


In [ ]:
print(a[1,-2]) #print the second last element in the second row

13


In [ ]:
# Get everything in a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [ ]:
# Get all elements in a specific column
print(a[:,3])

[ 4 11]


In [ ]:
# [startindex:endindex:steps]
print(a[0,1:5:2])

[2 4]


In [ ]:
# Replace a value
a[1,6] = 15
print(a)

a[:,3] = [4]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 15]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10  4 12 13 15]]


In [ ]:
# Accessing elements in a 3D array
c = np.array([
    [[3,4],[2,8]],
    [[1,2],[6,7]]
])
print(c)
print(c[1,0,1])

[[[3 4]
  [2 8]]

 [[1 2]
  [6 7]]]
2


In [ ]:
print(c[1,0,0])

1


In [ ]:
c.shape

(2, 2, 2)

In [ ]:
#Replacing a value
c[:,1,:] = [[9,9],[8,8]]
print(c)

[[[3 4]
  [9 9]]

 [[1 2]
  [8 8]]]


In [ ]:
c[:,:,1] = [[6,6],[7,7]]
print(c)

[[[3 6]
  [2 6]]

 [[1 7]
  [6 7]]]


In [ ]:
c[1,0,1] = 5
print(c)

[[[3 4]
  [9 9]]

 [[1 5]
  [8 8]]]


In [ ]:
c[0,:,1] = 2
print(c)

[[[3 2]
  [9 2]]

 [[1 5]
  [8 8]]]


**Different types of arrays**

In [ ]:
#All ones
np.ones((2,3,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [ ]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.87679851, 0.91914198],
       [0.71503556, 0.8011006 ],
       [0.24304271, 0.48274542],
       [0.18189051, 0.2912652 ]])

In [ ]:
# Random integerss
np.random.randint(10,size=(2,2)) # 10 means random numbers from 0-10

array([[8, 1],
       [5, 3]])

In [ ]:
# Copying arrays
a = np.array([1,2,3])
b = a
b[0] = 76
print(b)
print(a)

[76  2  3]
[76  2  3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 76
print(b)
print(a)

[76  2  3]
[1 2 3]


**Maths Using Arrays**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# Add
print(a + 2)

[3 4 5]


In [ ]:
# subtract
print(a-2)

[-1  0  1]


In [ ]:
# division
print(a/2)

[0.5 1.  1.5]


In [ ]:
# Multiplacation
print(a*2)

[2 4 6]


In [ ]:
#Power
a ** 2

array([1, 4, 9])

In [ ]:
# cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
b = np.array([2,4,5])
print(a)
print(b)
print("\n")
print(a+b)

[76  2  3]
[2 4 5]


[78  6  8]


In [ ]:
# They have to be of the same shape
a = np.array([2,4,6,4])
b = np.array([3,4,5])


**Statistics**

In [ ]:
a = np.array([[2,3,4,5],[54,6,33,2]])
print(np.min(a))
print(np.max(a))
print(np.min(a,axis=1))


2
54
[2 2]


**Reshaping**

In [ ]:
a = np.array([[2,3,4,5],[54,6,33,2]])
a.reshape((4,2))

array([[ 2,  3],
       [ 4,  5],
       [54,  6],
       [33,  2]])